import type { Parcel, Settings, SourceHealth } from "./types";

const now = new Date();
const isoHoursAgo = (hours: number) => new Date(now.getTime() - hours * 3_600_000).toISOString();
const isoDateFromNow = (days: number) => new Date(now.getTime() + days * 86_400_000).toISOString().slice(0, 10);

export const mockParcels: Parcel[] = [
  {
    id: "demo-pickup",
    name: "Birthday gift",
    tracking_number: "JD000000000DE",
    carrier: "dhl_paket_de",
    destination_country: "DE",
    destination_postcode: "10997",
    shipment_date: null,
    international: false,
    generation: 1,
    status: "ready_for_pickup",
    raw_status: "READY_FOR_PICKUP",
    summary: "Ready for pickup at the selected parcel shop",
    sender: "Example shop",
    estimate: null,
    international_tracking_url: null,
    events: [
      { source_id: null, raw_status: null, status: "ready_for_pickup", description: "Ready for pickup at the selected parcel shop", location: "Berlin", timestamp: isoHoursAgo(3) },
      { source_id: null, raw_status: null, status: "in_transit", description: "Arrived at the delivery depot", location: "Berlin", timestamp: isoHoursAgo(17) },
      { source_id: null, raw_status: null, status: "announced", description: "Shipment announced electronically", location: null, timestamp: isoHoursAgo(43) },
    ],
    fetch_state: "idle",
    last_error: null,
    created_at: isoHoursAgo(20),
    updated_at: isoHoursAgo(3),
    archived_at: null,
    last_checked_at: isoHoursAgo(0.2),
    last_success_at: isoHoursAgo(0.2),
    next_check_at: isoHoursAgo(-0.8),
    parser_version: "dhl-paket-de/2026-09-14.3",
  },
  {
    id: "demo-attempted",
    name: "Coffee grinder",
    tracking_number: "H00000000000001",
    carrier: "hermes_de",
    destination_country: "DE",
    destination_postcode: "80331",
    shipment_date: null,
    international: false,
    generation: 1,
    status: "delivery_attempted",
    raw_status: "DELIVERY_ATTEMPTED",
    summary: "Delivery was attempted; a new attempt is planned",
    sender: "Coffee Roasters",
    estimate: null,
    international_tracking_url: null,
    events: [
      { source_id: null, raw_status: null, status: "delivery_attempted", description: "Delivery was attempted; a new attempt is planned", location: "Munich", timestamp: isoHoursAgo(6) },
      { source_id: null, raw_status: null, status: "out_for_delivery", description: "Loaded onto the delivery vehicle", location: "Munich", timestamp: isoHoursAgo(12) },
      { source_id: null, raw_status: null, status: "in_transit", description: "Processed at the logistics centre", location: "Munich", timestamp: isoHoursAgo(36) },
    ],
    fetch_state: "idle",
    last_error: null,
    created_at: isoHoursAgo(50),
    updated_at: isoHoursAgo(6),
    archived_at: null,
    last_checked_at: isoHoursAgo(0.4),
    last_success_at: isoHoursAgo(0.4),
    next_check_at: isoHoursAgo(-0.6),
    parser_version: "hermes-de/2026-09-14.2",
  },
  {
    id: "demo-exception",
    name: "Desk lamp",
    tracking_number: "CY000000000BE",
    carrier: "dhl_paket_de",
    destination_country: "BE",
    destination_postcode: null,
    shipment_date: null,
    international: true,
    generation: 1,
    status: "exception",
    raw_status: "EXCEPTION",
    summary: "The carrier reported a problem with this shipment",
    sender: "Example shop",
    estimate: null,
    international_tracking_url: null,
    events: [
      { source_id: null, raw_status: null, status: "exception", description: "Address clarification requested by the carrier", location: "Liège, Belgium", timestamp: isoHoursAgo(4) },
      { source_id: null, raw_status: null, status: "in_transit", description: "Processed at the international parcel centre", location: "Köln, Germany", timestamp: isoHoursAgo(31) },
      { source_id: null, raw_status: null, status: "announced", description: "Shipment announced electronically", location: null, timestamp: isoHoursAgo(55) },
    ],
    fetch_state: "source_error",
    last_error: "Source payload changed while refreshing.",
    created_at: isoHoursAgo(54),
    updated_at: isoHoursAgo(4),
    archived_at: null,
    last_checked_at: isoHoursAgo(0.7),
    last_success_at: isoHoursAgo(4),
    next_check_at: isoHoursAgo(-0.3),
    parser_version: "dhl-paket-de/2026-09-14.3",
  },
  {
    id: "demo-transit",
    name: "Winter coat",
    tracking_number: "H00000000000002",
    carrier: "hermes_de",
    destination_country: "DE",
    destination_postcode: "04109",
    shipment_date: null,
    international: false,
    generation: 1,
    status: "in_transit",
    raw_status: "IN_TRANSIT",
    summary: "The shipment is moving through the carrier network",
    sender: "Example shop",
    estimate: { from: "08:00", until: "12:00", date: isoDateFromNow(1) },
    international_tracking_url: null,
    events: [
      { source_id: null, raw_status: null, status: "in_transit", description: "Departed the logistics centre", location: "Halle, Germany", timestamp: isoHoursAgo(5) },
      { source_id: null, raw_status: null, status: "announced", description: "The shipment was announced electronically to Hermes", location: null, timestamp: isoHoursAgo(38) },
    ],
    fetch_state: "idle",
    last_error: null,
    created_at: isoHoursAgo(72),
    updated_at: isoHoursAgo(5),
    archived_at: null,
    last_checked_at: isoHoursAgo(0.9),
    last_success_at: isoHoursAgo(0.9),
    next_check_at: isoHoursAgo(-1.1),
    parser_version: "hermes-de/2026-09-14.2",
  },
  {
    id: "demo-dhl",
    name: "Studio headphones",
    tracking_number: "CY000000000DE",
    carrier: "dhl_paket_de",
    destination_country: "PL",
    destination_postcode: null,
    shipment_date: null,
    international: true,
    generation: 1,
    status: "out_for_delivery",
    raw_status: "OUT_FOR_DELIVERY",
    summary: "Loaded onto the delivery vehicle",
    sender: null,
    estimate: { from: "12:00", until: "16:00", date: now.toISOString().slice(0, 10) },
    international_tracking_url: null,
    events: [
      { source_id: null, raw_status: null, status: "out_for_delivery", description: "Loaded onto the delivery vehicle", location: "Poznań, Poland", timestamp: isoHoursAgo(1) },
      { source_id: null, raw_status: null, status: "in_transit", description: "Processed at the parcel centre", location: "Poznań, Poland", timestamp: isoHoursAgo(9) },
      { source_id: null, raw_status: null, status: "announced", description: "Shipment announced electronically", location: null, timestamp: isoHoursAgo(32) },
    ],
    fetch_state: "idle",
    last_error: null,
    created_at: isoHoursAgo(48),
    updated_at: isoHoursAgo(1),
    archived_at: null,
    last_checked_at: isoHoursAgo(0.1),
    last_success_at: isoHoursAgo(0.1),
    next_check_at: isoHoursAgo(-0.4),
    parser_version: "dhl-paket-de/2026-09-14.3",
  },
  {
    id: "demo-hermes",
    name: "Kitchen shelves",
    tracking_number: "88888888888888",
    carrier: "hermes_de",
    destination_country: "ES",
    destination_postcode: null,
    shipment_date: null,
    international: true,
    generation: 1,
    status: "announced",
    raw_status: "ANNOUNCED",
    summary: "The shipment was announced electronically to Hermes.",
    sender: null,
    estimate: null,
    international_tracking_url: "https://www.correos.es/es/en/tools/tracker/items/details?tracking-number=EXAMPLE",
    events: [
      { source_id: null, raw_status: "ANNOUNCED", status: "announced", description: "The shipment was announced electronically to Hermes.", location: null, timestamp: isoHoursAgo(2) },
    ],
    fetch_state: "idle",
    last_error: null,
    created_at: isoHoursAgo(2),
    updated_at: isoHoursAgo(2),
    archived_at: null,
    last_checked_at: isoHoursAgo(0.25),
    last_success_at: isoHoursAgo(0.25),
    next_check_at: isoHoursAgo(-1.75),
    parser_version: "hermes-de/2026-09-14.2",
  },
  {
    id: "demo-delivered",
    name: "Running shoes",
    tracking_number: "00340000000000000000",
    carrier: "dhl_paket_de",
    destination_country: "DE",
    destination_postcode: null,
    shipment_date: null,
    international: false,
    generation: 1,
    status: "delivered",
    raw_status: "DELIVERED",
    summary: "Delivered successfully",
    sender: "Example shop",
    estimate: null,
    international_tracking_url: null,
    events: [
      { source_id: null, raw_status: null, status: "delivered", description: "Delivered successfully", location: "Berlin", timestamp: isoHoursAgo(24) },
    ],
    fetch_state: "idle",
    last_error: null,
    created_at: isoHoursAgo(96),
    updated_at: isoHoursAgo(24),
    archived_at: null,
    last_checked_at: isoHoursAgo(24),
    last_success_at: isoHoursAgo(24),
    next_check_at: null,
    parser_version: "dhl-paket-de/2026-09-14.3",
  },
  {
    id: "demo-queued",
    name: "Garden tools",
    tracking_number: "00340000000000000042",
    carrier: "dhl_paket_de",
    destination_country: "DE",
    destination_postcode: null,
    shipment_date: null,
    international: false,
    generation: 1,
    status: "unknown",
    raw_status: null,
    summary: "Waiting for first update",
    sender: null,
    estimate: null,
    international_tracking_url: null,
    events: [],
    fetch_state: "queued",
    last_error: null,
    created_at: isoHoursAgo(1),
    updated_at: isoHoursAgo(1),
    archived_at: null,
    last_checked_at: null,
    last_success_at: null,
    next_check_at: isoHoursAgo(-0.1),
    parser_version: null,
  },
  {
    id: "demo-archived",
    name: "Old books",
    tracking_number: "00340000000000000084",
    carrier: "dhl_paket_de",
    destination_country: "DE",
    destination_postcode: null,
    shipment_date: null,
    international: false,
    generation: 1,
    status: "delivered",
    raw_status: "DELIVERED",
    summary: "Delivered successfully",
    sender: "Example shop",
    estimate: null,
    international_tracking_url: null,
    events: [
      { source_id: null, raw_status: null, status: "delivered", description: "Delivered successfully", location: "Berlin", timestamp: isoHoursAgo(170) },
    ],
    fetch_state: "idle",
    last_error: null,
    created_at: isoHoursAgo(240),
    updated_at: isoHoursAgo(170),
    archived_at: isoHoursAgo(120),
    last_checked_at: isoHoursAgo(170),
    last_success_at: isoHoursAgo(170),
    next_check_at: null,
    parser_version: "dhl-paket-de/2026-09-14.3",
  },
];

export const mockSettings: Settings = {
  theme: "system",
  notifyDelivered: true,
  notifyPickup: true,
  notifyProblems: true,
  notifyOutForDelivery: false,
  startWithWindows: false,
  startMinimized: false,
};

export const mockSourceHealth: SourceHealth[] = [
  { carrier: "dhl_paket_de", label: "DHL", enabled: true, parser_version: "dhl-paket-de/2026-09-14.3", last_success_at: isoHoursAgo(0.1), limitation: "Validated with one delivered international parcel." },
  { carrier: "hermes_de", label: "Hermes Germany", enabled: true, parser_version: "hermes-de/2026-09-14.2", last_success_at: isoHoursAgo(0.25), limitation: "Validated through announced state; later states remain fixture-tested." },
];
