import type { Parcel, Settings, SourceHealth } from "./types";

const now = new Date();
const isoHoursAgo = (hours: number) => new Date(now.getTime() - hours * 3_600_000).toISOString();

export const mockParcels: Parcel[] = [
  {
    id: "demo-dhl",
    name: "Studio headphones",
    tracking_number: "CY000000000DE",
    carrier: "dhl_paket_de",
    destination_country: "PL",
    destination_postcode: null,
    shipment_date: null,
    international: true,
    generation: 1,
    status: "out_for_delivery",
    raw_status: "OUT_FOR_DELIVERY",
    summary: "Loaded onto the delivery vehicle",
    sender: null,
    estimate: { from: "12:00", until: "16:00", date: now.toISOString().slice(0, 10) },
    international_tracking_url: null,
    events: [
      { source_id: null, raw_status: null, status: "out_for_delivery", description: "Loaded onto the delivery vehicle", location: "Poznań, Poland", timestamp: isoHoursAgo(1) },
      { source_id: null, raw_status: null, status: "in_transit", description: "Processed at the parcel centre", location: "Poznań, Poland", timestamp: isoHoursAgo(9) },
      { source_id: null, raw_status: null, status: "announced", description: "Shipment announced electronically", location: null, timestamp: isoHoursAgo(32) },
    ],
    fetch_state: "idle",
    last_error: null,
    created_at: isoHoursAgo(48),
    updated_at: isoHoursAgo(1),
    archived_at: null,
    last_checked_at: isoHoursAgo(0.1),
    last_success_at: isoHoursAgo(0.1),
    next_check_at: isoHoursAgo(-0.4),
    parser_version: "dhl-paket-de/2026-09-14.3",
  },
  {
    id: "demo-hermes",
    name: "Kitchen shelves",
    tracking_number: "88888888888888",
    carrier: "hermes_de",
    destination_country: "ES",
    destination_postcode: null,
    shipment_date: null,
    international: true,
    generation: 1,
    status: "announced",
    raw_status: "ANNOUNCED",
    summary: "The shipment was announced electronically to Hermes.",
    sender: null,
    estimate: null,
    international_tracking_url: "https://www.correos.es/es/en/tools/tracker/items/details?tracking-number=EXAMPLE",
    events: [
      { source_id: null, raw_status: "ANNOUNCED", status: "announced", description: "The shipment was announced electronically to Hermes.", location: null, timestamp: isoHoursAgo(2) },
    ],
    fetch_state: "idle",
    last_error: null,
    created_at: isoHoursAgo(2),
    updated_at: isoHoursAgo(2),
    archived_at: null,
    last_checked_at: isoHoursAgo(0.25),
    last_success_at: isoHoursAgo(0.25),
    next_check_at: isoHoursAgo(-1.75),
    parser_version: "hermes-de/2026-09-14.2",
  },
  {
    id: "demo-delivered",
    name: "Running shoes",
    tracking_number: "00340000000000000000",
    carrier: "dhl_paket_de",
    destination_country: "DE",
    destination_postcode: null,
    shipment_date: null,
    international: false,
    generation: 1,
    status: "delivered",
    raw_status: "DELIVERED",
    summary: "Delivered successfully",
    sender: "Example shop",
    estimate: null,
    international_tracking_url: null,
    events: [
      { source_id: null, raw_status: null, status: "delivered", description: "Delivered successfully", location: "Berlin", timestamp: isoHoursAgo(24) },
    ],
    fetch_state: "idle",
    last_error: null,
    created_at: isoHoursAgo(96),
    updated_at: isoHoursAgo(24),
    archived_at: null,
    last_checked_at: isoHoursAgo(24),
    last_success_at: isoHoursAgo(24),
    next_check_at: null,
    parser_version: "dhl-paket-de/2026-09-14.3",
  },
];

export const mockSettings: Settings = {
  theme: "system",
  notifyDelivered: true,
  notifyPickup: true,
  notifyProblems: true,
  notifyOutForDelivery: false,
  startWithWindows: false,
  startMinimized: false,
};

export const mockSourceHealth: SourceHealth[] = [
  { carrier: "dhl_paket_de", label: "DHL", enabled: true, parser_version: "dhl-paket-de/2026-09-14.3", last_success_at: isoHoursAgo(0.1), limitation: "Validated with one delivered international parcel." },
  { carrier: "hermes_de", label: "Hermes Germany", enabled: true, parser_version: "hermes-de/2026-09-14.2", last_success_at: isoHoursAgo(0.25), limitation: "Validated through announced state; later states remain fixture-tested." },
];
